package com.dauphine.flight.model

import org.apache.spark.sql.types._

object WeatherSchema {

  val weatherSchema = StructType(Array(
    StructField("WBAN", IntegerType, true),
    StructField("DATETIME_RND", TimestampType, true),
    StructField("Visibility", StringType, true),
    StructField("DryBulbCelsius", StringType, true),
    StructField("RelativeHumidity", StringType, true),
    StructField("WindSpeed", StringType, true),
    StructField("RecordType", IntegerType, true),
    StructField("Altimeter", DoubleType, true),
    StructField("clearSky", IntegerType, true),
    StructField("fewClouds", IntegerType, true),
    StructField("scatterClouds", IntegerType, true),
    StructField("brokenClouds", IntegerType, true),
    StructField("overCast", IntegerType, true),
    StructField("obscuredSky", IntegerType, true),
    StructField("Sky1_height", IntegerType, true),
    StructField("Sky1_height1", IntegerType, true),
    StructField("Visibility1", StringType, true),
    StructField("DryBulbCelsius1", StringType, true),
    StructField("RelativeHumidity1", StringType, true),
    StructField("WindSpeed1", StringType, true),
    StructField("RecordType1", IntegerType, true),
    StructField("Altimeter1", DoubleType, true),
    StructField("clearSky1", IntegerType, true),
    StructField("fewClouds1", IntegerType, true),
    StructField("scatterClouds1", IntegerType, true),
    StructField("brokenClouds1", IntegerType, true),
    StructField("overCast1", IntegerType, true),
    StructField("obscuredSky1", IntegerType, true),
    StructField("Sky1_height2", IntegerType, true),
    StructField("Visibility2", StringType, true),
    StructField("DryBulbCelsius2", StringType, true),
    StructField("RelativeHumidity2", StringType, true),
    StructField("WindSpeed2", StringType, true),
    StructField("RecordType2", IntegerType, true),
    StructField("Altimeter2", DoubleType, true),
    StructField("clearSky2", IntegerType, true),
    StructField("fewClouds2", IntegerType, true),
    StructField("scatterClouds2", IntegerType, true),
    StructField("brokenClouds2", IntegerType, true),
    StructField("overCast2", IntegerType, true),
    StructField("obscuredSky2", IntegerType, true),
    StructField("Sky1_height3", IntegerType, true),
    StructField("Visibility3", StringType, true),
    StructField("DryBulbCelsius3", StringType, true),
    StructField("WindSpeed3", StringType, true),
    StructField("RelativeHumidity3", StringType, true),
    StructField("RecordType3", IntegerType, true),
    StructField("Altimeter3", DoubleType, true),
    StructField("clearSky3", IntegerType, true),
    StructField("fewClouds3", IntegerType, true),
    StructField("scatterClouds3", IntegerType, true),
    StructField("brokenClouds3", IntegerType, true),
    StructField("overCast3", IntegerType, true),
    StructField("obscuredSky3", IntegerType, true),
    StructField("CalmWeather", DoubleType, true),
  ))

}
